name: convL2LFlows
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch==1.13
  - cudatoolkit=10.2
  - h5py==3.10
  - numpy==1.26
  - matplotlib==3.8
  - PyYAML==6.0
  - scikit-learn==1.3
  - scipy==1.11
  - torchinfo==1.8
  - torchmetrics==1.2
  - pip
  - pip:
    - -e git+https://github.com/ThorstenBuss/nflows.git@138f86830e161bb0095dbb5cdd51871b769ea5b7#egg=nflows
